FROM node:20.11.1-slim

WORKDIR /app

# Copy package files first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

EXPOSE 3000

# Set environment variable for development
ENV GENERATE_SOURCEMAP=false
ENV REACT_APP_PWA=true

CMD ["npm", "start"]
