# Generated by Django 5.2 on 2025-04-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('student', '0004_alter_student_modality_delete_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hour', models.IntegerField(choices=[(6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')], verbose_name='Horário')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='student.student')),
            ],
            options={
                'verbose_name': 'Horário do Aluno',
                'verbose_name_plural': 'Horários dos Alunos',
                'ordering': ['weekday', 'hour'],
                'unique_together': {('student', 'weekday', 'hour')},
            },
        ),
    ]
