# Generated by Django 5.2 on 2025-04-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0001_initial'),
        ('student', '0003_modality_student_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='modality.modality', verbose_name='Modalidade'),
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
    ]
