# Generated by Django 5.2 on 2025-04-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_modality_delete_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Data de referência para pagamento mensal', null=True, verbose_name='Data de Referência do Pagamento'),
        ),
        migrations.AddField(
            model_name='student',
            name='session_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade de sessões disponíveis para pagamento por sessão', null=True, verbose_name='Quantidade de Sessões'),
        ),
    ]
