# Generated by Django 5.2 on 2025-04-29 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_payment_date_student_session_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentagem de comissão (entre 0 e 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comissão (%)'),
        ),
    ]
