# Generated by Django 5.2 on 2025-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_type',
            field=models.CharField(choices=[('PRE', 'Pré-pago'), ('POS', 'Pós-pago')], default='PRE', max_length=3, verbose_name='Tipo de Pagamento'),
        ),
    ]
