# Generated by Django 5.2 on 2025-05-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0004_alter_modality_options_modality_payment_type'),
        ('student', '0007_student_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='modality.modality', verbose_name='Modalidade'),
        ),
    ]
