# Generated by Django 5.2 on 2025-05-14 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_modality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='student',
            name='payment_day',
            field=models.PositiveIntegerField(blank=True, help_text='Dia do mês para pagamento (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Pagamento'),
        ),
    ]
