# Generated by Django 5.2 on 2025-05-07 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Data da Transferência')),
                ('total_commission_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de Comissão Devido')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Transferido')),
                ('description', models.TextField(help_text='Descrição sobre a transferência realizada', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physiotherapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payments', to='physiotherapist.physiotherapist', verbose_name='Fisioterapeuta')),
            ],
            options={
                'verbose_name': 'Pagamento de Comissão',
                'verbose_name_plural': 'Pagamentos de Comissões',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
