# Generated by Django 5.2 on 2025-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_cliniccommissionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniccommissionpayment',
            name='payments',
            field=models.ManyToManyField(related_name='commission_payments', to='payment.payment', verbose_name='Pagamentos Incluídos'),
        ),
    ]
