# Generated by Django 5.2 on 2025-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cliniccommissionpayment_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniccommissionpayment',
            name='status',
            field=models.CharField(choices=[('awaiting_approval', 'Aguardando Aprovação'), ('approved', 'Aprovado')], default='awaiting_approval', max_length=20, verbose_name='Status'),
        ),
    ]
