# Generated by Django 5.2 on 2025-04-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='active',
        ),
    ]
