# Generated by Django 5.2 on 2025-04-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0002_remove_modality_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='frequency',
        ),
    ]
