# Generated by Django 5.2 on 2025-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modality', '0003_remove_modality_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modality',
            options={'ordering': ['name'], 'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AddField(
            model_name='modality',
            name='payment_type',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('SESSION', 'Sessão')], default='MONTHLY', max_length=10, verbose_name='Tipo de Pagamento'),
        ),
    ]
